- hosts: arch
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: create personal user
      user:
        name: "{{ user }}"
        password: "{{ password }}"
      tags: ['install']
    - name: create aur management user
      user:
        name: aur_user
        group: wheel
        home: /var/lib/aurman
        system: yes
        shell: /bin/nologin
      tags: ['install']
    - name: setup sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "# This sequence is important for Ansible!\n%wheel ALL=(ALL) ALL\naur_user ALL=(ALL) NOPASSWD: ALL"
      tags: ['install']
    - name: Install core packages
      pacman:
        name: "{{ item }}"
        state: present
      with_items: "{{ core_packages }}"
    - name: install aur packages
      aur:
        name: "{{ item }}"
        user: aur_user
        skip_pgp: yes
      with_items: "{{ aur_packages }}"
