- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  vars_prompt:
    - name: "user"
      prompt: "Username to create"
      default: "bas"
    - name: "create"
      prompt: "Do we need to create it? (true / false)"
      default: "true"
  tasks:
    - name: create personal group
      group:
        name: "{{ user }}"
      tags: ['install']
      when: create == 'true'
    - name: create personal user
      user:
        name: "{{ user }}"
        password: "{{ password }}"
        group: bas
        groups: wheel
        shell: /bin/zsh
      tags: ['install']
      when: create == 'true'
    - name: import arch linux setup
      import_tasks: arch.yml
      when: ansible_distribution == "Archlinux"
    - name: clone dotfiles
      git:
        repo: https://github.com/BasLangenberg/dots.git
        path: "/home/{{ user }}/dots"
    - name: link dotfiles
      file:
        src: "/home/{{ user }}/dots/files/{{ file}}"
        path: "/home/{{ user }}/{{ file }}"
        ensure: link
        owner: "{{ user }}"
        group: "{{ user }}"
      with_items:
        - .zshrc
