- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: create personal group
      group:
        name: "{{ user }}"
      tags: ['install']
      when: ansible_env.SETUP_USERNAME is defined
    - name: create personal user
      user:
        name: "{{ user }}"
        password: "{{ password }}"
        group: "{{ user }}"
        groups: wheel
        shell: /bin/zsh
      tags: ['install']
      when: ansible_env.SETUP_USERNAME is defined
    - name: import arch linux setup
      import_tasks: arch.yml
      when: ansible_distribution == "Archlinux"
    - name: clone dotfiles
      git:
        repo: https://github.com/BasLangenberg/dots.git
        dest: "/home/{{ user }}/dots"
    - name: update permissions
      file:
        path: "/home/{{ user }}/dots"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: true
    - name: link dotfiles
      file:
        src: "/home/{{ user }}/dots/files/{{ item }}"
        path: "/home/{{ user }}/{{ item }}"
        state: link
        owner: "{{ user }}"
        group: "{{ user }}"
      with_items:
        - .zshrc
